# Generated by Django 3.0 on 2020-02-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ischolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='options4',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AlterField(
            model_name='anwser',
            name='anwser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ischolar.Question', verbose_name='answer to questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ischolar.Subjects', verbose_name='list of subejects'),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
