# Generated by Django 3.0 on 2020-02-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ischolar', '0002_auto_20200201_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anwser',
        ),
    ]
